### ISSUE TITLE
EventViewModelBase Backing Field causes XamlObjectWriterException

### ISSUE THREAD

**Issue by FuNkNaN** [fsprojects/FSharp.ViewModule#27] opened 2017-01-15 12:33 UTC
### Description

After updating from FSharp.ViewModule v0.9.9.3 to v1.0.4.0, using a backing field in EventViewModelBase<'a> causes a XamlObjectWriterException.

### Repro steps

1. Step A

    [Dummy project](https://github.com/FuNkNaN/CookieFactory) runs under FSharp.ViewModule 0.9.9.3.

2. Step B

    Updating to FSharp.ViewModule 1.0.4.0 and making necessary changes:

In MainViewModel.fs

_Changing_
```
open FSharp.ViewModule
``` 
_To_

```
open ViewModule
open ViewModule.FSharp
```

### Related information 

After [creating a wrapper for the vm](https://github.com/fsprojects/FSharp.ViewModule/issues/22), I get the following output:

> Exception thrown: 'System.InvalidCastException' in FSharp.Core.dll
> Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
> Exception thrown: 'System.Reflection.TargetInvocationException' in System.dll
> System.Windows.Data Error: 17 : Cannot get 'ViewModel' value (type 'MainViewModel') from '' (type 'Wrapper'). BindingExpression:Path=ViewModel; DataItem='Wrapper' (HashCode=64844482); target element is 'Window' (Name=''); target property is 'DataContext' (type 'Object') TargetInvocationException:'System.Reflection.TargetInvocationException: Property accessor 'ViewModel' on object 'View.Wrapper' threw the following exception:'Unable to cast object of type 'ViewModel.MainViewModel' to type 'ViewModule.ViewModelPropertyFactory'.' ---> System.InvalidCastException: Unable to cast object of type 'ViewModel.MainViewModel' to type 'ViewModule.ViewModelPropertyFactory'.
>    at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
>    at ViewModule.FSharp.EventExtensions.IViewModelPropertyFactory.Backing[a](IViewModelPropertyFactory x, FSharpExpr prop, a defaultValue, FSharpOption`1 validate)
>    at ViewModel.MainViewModel..ctor() in C:\data\F#\Code\Cookie\CookieFactory\CookieFactory\MainViewModel.fs:line 10
>    at View.Wrapper.get_ViewModel() in C:\data\F#\Code\Cookie\CookieFactory\CookieFactory\MainWindow.xaml.fs:line 8
>    --- End of inner exception stack trace ---
>    at System.ComponentModel.ReflectPropertyDescriptor.GetValue(Object component)
>    at MS.Internal.Data.ValueTable.GetValue(Object item, PropertyDescriptor pd, Boolean indexerIsNext)
>    at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
>    at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'

**Comment by brianberns** [comment] 2017-01-16 15:28
I'm having exactly the same issue.

**Comment by ReedCopsey** [comment] 2017-01-16 23:52
Thanks for the detailed report - I've managed to duplicate - looking at how to correct this.

It appears that the redirection for C# support in EventViewModel wasn't done quite right - it works for the commands, but not for anything else.  I should be able to rework how this functions, but I'm still trying to figure out where all it needs modifications.

**Comment by ReedCopsey** [comment] 2017-01-16 23:56
@anton-pt Just in case you have any input... The issue is that EventViewModelBase redefines `Factory`, and shadows the base class type's property, which in turn causes things to go haywire at runtime when the extension methods (which expect the base types) are used...

**Comment by ReedCopsey** [comment] 2017-01-17 19:50
Should be fixed in 1.0.5 - up on NuGet 

https://www.nuget.org/packages/FSharp.ViewModule.Core/

**Closed by ReedCopsey** 2017-01-17 19:50 UTC

**Comment by FuNkNaN** [comment] 2017-01-17 22:06
Nice job juggling those factory types. Great open source!

**Comment by ReedCopsey** [comment] 2017-01-17 22:07
@FuNkNaN TBH, I'm not exactly happy with this approach, but it works for now, at least.  I'd like to come up with a better way to handle this, but not sure how to make it work given the order of construction.
