### ISSUE TITLE
XAML editor indicates DataContext does not support view model's type

### ISSUE THREAD

**Issue by amazingant** [fsprojects/FSharp.ViewModule#22] opened 2016-06-28 19:44 UTC
### Description

Using a view-model that inherits `ViewModelBase` and setting the data context to that type, Visual Studio reports `Property 'DataContext' does not support values of type 'MainViewModel'.`
### Repro steps

Please provide the steps required to reproduce the problem
1. Point a view to a view-model that inherits from `ViewModelBase` via `<Window.DataContext><local:MainViewModel /></Window.DataContext>`
2. Rebuild solution
3. Close/reopen Visual Studio, or kill `XDesProc.exe` via Task Manager to get the WPF design view to load the latest binary
### Expected behavior

Everything should load normall
### Actual behavior

The Error List in Visual Studio shows the error mentioned above, and provides a colored squiggly underneath `<local:MainViewModel />`
### Known workarounds
- Not inheriting from `ViewModelBase` and then doing the rebuild & close/open dance with Visual Studio makes the error go away, but makes the view-model much less useful
- Ignoring the error works fine, as the application still builds and runs fine
### Related information
- Running on Windows 10 Pro v 1511 with Visual Studio 2015 w/ Update 2
- Using NuGet package version `0.9.9.3`
- Targeting .NET 4.5 and F# 4.4.0.0, local system has .NET 4.6.1

**Comment by ReedCopsey** [comment] 2016-06-29 22:17
I'm fairly certain this is a regression in Visual Studio's XAML editor itself, not related to FSharp.ViewModule.  I've seen this (and some other oddities), but have no idea why that'd even be possible as an error message.

DataContext is typed as System.Object, so _anything_ should be a valid DataContext.

**Comment by amazingant** [comment] 2016-07-02 14:50
I had assumed the same when I wrote this up. Don't suppose you know a place I could report this to the VS people without it being ignored or `wontfix`'d?

**Comment by ReedCopsey** [comment] 2017-01-04 23:12
Closing because it's out of my hands - hopefully VS will fix.

**Closed by ReedCopsey** 2017-01-04 23:12 UTC
Labels: wontfix

**Comment by FuNkNaN** [comment] 2017-01-05 16:46
There's a workaround to avoid the error.

In the xaml.fs file add

```
type CompositionRoot() =
    member __.ViewModel = Space.ViewModels.MainViewModel() // i.e. the type’s full name
```

Then in the xaml file change

    <Window.DataContext>
        <local:MainViewModel/>
    </Window.DataContext>

to

    <Window.Resources>
        <ResourceDictionary>
            <local:CompositionRoot x:Key="CompositionRoot"/>
            
        </ResourceDictionary>
    </Window.Resources>
    <Window.DataContext>
        <Binding Source="{StaticResource CompositionRoot}" Path="ViewModel"/>
    </Window.DataContext>

Seems to resolve the issue at design time. Hope it helps.
